// <auto-generated />
using CollegeWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeWebsite.Data.Migrations.ProgrammesDb
{
    [DbContext(typeof(ProgrammesDbContext))]
    partial class ProgrammesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeWebsite.Entities.Programmes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PicureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Programmes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "B.Tech | M.Tech | P.hD",
                            PicureUrl = "http://cpuh.in/wp-content/uploads/2022/02/engineering.jpg",
                            Title = "Engineering & Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "B.Sc. (PCMB) | M.Sc. (PCMB)| P.hD",
                            PicureUrl = "http://cpuh.in/wp-content/uploads/2022/02/science.jpg",
                            Title = "Basic & Applied Sciences"
                        },
                        new
                        {
                            Id = 3,
                            Description = "B.Com | M.Com | BBA | MBA| P.hD",
                            PicureUrl = "http://cpuh.in/wp-content/uploads/2022/02/management.jpg",
                            Title = "Business & Management Studies"
                        },
                        new
                        {
                            Id = 4,
                            Description = "BCA I MCA | B.Sc.(IT) | M.Sc.(IT) |DCA | PGDCA",
                            PicureUrl = "http://cpuh.in/wp-content/uploads/2022/03/csaw-18-laptop.png",
                            Title = "Computer Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
