// <auto-generated />
using CollegeWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeWebsite.Data.Migrations
{
    [DbContext(typeof(CollegeWebsiteDbContext))]
    [Migration("20230102130645_renamed college to admissions")]
    partial class renamedcollegetoadmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeWebsite.Entities.Admissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumberExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admissions", (string)null);
                });

            modelBuilder.Entity("CollegeWebsite.Entities.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = "BCA"
                        },
                        new
                        {
                            Id = 2,
                            Course = "MCA"
                        },
                        new
                        {
                            Id = 3,
                            Course = "BBA"
                        },
                        new
                        {
                            Id = 4,
                            Course = "MBA"
                        },
                        new
                        {
                            Id = 5,
                            Course = "Bsc"
                        },
                        new
                        {
                            Id = 6,
                            Course = "Msc"
                        },
                        new
                        {
                            Id = 7,
                            Course = "PhD"
                        });
                });

            modelBuilder.Entity("CollegeWebsite.Entities.Programmes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PicureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Programmes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "B.Tech | M.Tech | P.hD",
                            PicureUrl = "~/images/programmes/engineering.jpg",
                            Title = "Engineering & Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "B.Sc. (PCMB) | M.Sc. (PCMB)| P.hD",
                            PicureUrl = "~/images/programmes/science.jpg",
                            Title = "Basic & Applied Sciences"
                        },
                        new
                        {
                            Id = 3,
                            Description = "B.Com | M.Com | BBA | MBA| P.hD",
                            PicureUrl = "~/images/programmes/management.jpg",
                            Title = "Business & Management Studies"
                        },
                        new
                        {
                            Id = 4,
                            Description = "BCA I MCA | B.Sc.(IT) | M.Sc.(IT) |DCA | PGDCA",
                            PicureUrl = "~/images/programmes/computer.png",
                            Title = "Computer Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
